const flavors = [ 
    { 
       id:1,
       flavor:"Vanilla Bean",
       img_url:"assets/vanilla-bean.jpg",
       type:"Classic",
       vegan:false,
       will_licks:5.0,
       logan_licks:5.0
    },
    { 
       id:2,
       flavor:"Belgian Chocolate",
       img_url:"assets/belgian-chocolate.jpg",
       type:"Chocolate",
       vegan:false,
       will_licks:4.0,
       logan_licks:3.0
    },
    { 
       id:3,
       flavor:"Coconut Caramel",
       img_url:"assets/coconut-caramel.jpg",
       type:"Caramel",
       vegan:true,
       will_licks:2.0,
       logan_licks:3.0
    },
    { 
       id:4,
       flavor:"Mint Chip",
       img_url:"assets/mint-chip.jpg",
       type:"Classic",
       vegan:false,
       will_licks:3.0,
       logan_licks:5.0
    },
    { 
       id:5,
       flavor:"Strawberry",
       img_url:"assets/strawberry.jpg",
       type:"Fruit",
       vegan:false,
       will_licks:2.0,
       logan_licks:2.0
    },
    { 
       id:6,
       flavor:"Mocha Almond Fudge",
       img_url:"assets/mocha-almond-fudge.jpg",
       type:"Nutty",
       vegan:false,
       will_licks:1.0,
       logan_licks:2.0
    },
    { 
       id:7,
       flavor:"Salted Caramel",
       img_url:"assets/salted-caramel.jpg",
       type:"Caramel",
       vegan:false,
       will_licks:4.0,
       logan_licks:2.0
    },
    { 
       id:8,
       flavor:"Mango Sorbet",
       img_url:"assets/mango-sorbet.jpg",
       type:"Fruit",
       vegan:true,
       will_licks:5.0,
       logan_licks:3.0
    },
    { 
       id:9,
       flavor:"Dulce De Leche",
       img_url:"assets/dulce-de-leche.jpg",
       type:"Exotic",
       vegan:false,
       will_licks:4.0,
       logan_licks:1.0
    },
    { 
       id:10,
       flavor:"Chocolate Chip Cookie Dough",
       img_url:"assets/chocolate-chip-cookie-dough.jpg",
       type:"Chocolate",
       vegan:false,
       will_licks:1.0,
       logan_licks:1.0
    },
    { 
       id:11,
       flavor:"Cookies 'n' Cream",
       img_url:"assets/cookies-n-cream.jpg",
       type:"Classic",
       vegan:false,
       will_licks:1.0,
       logan_licks:4.0
    },
    { 
       id:12,
       flavor:"Butter Pecan",
       img_url:"assets/butter-pecan.jpg",
       type:"Nutty",
       vegan:false,
       will_licks:3.0,
       logan_licks:5.0
    },
    { 
       id:13,
       flavor:"Amaretto Black Cherry Almond",
       img_url:"assets/amaretto-black-cherry-almond.jpg",
       type:"Exotic",
       vegan:false,
       will_licks:5.0,
       logan_licks:1.0
    },
    { 
       id:14,
       flavor:"Mocha Chocolate Cookie",
       img_url:"assets/mocha-chocolate-cookie.jpg",
       type:"Chocolate",
       vegan:true,
       will_licks:4.0,
       logan_licks:1.0
    },
    { 
       id:15,
       flavor:"Cherry",
       img_url:"assets/cherry.jpg",
       type:"Fruit",
       vegan:true,
       will_licks:1.0,
       logan_licks:5.0
    },
    { 
       id:16,
       flavor:"Espresso",
       img_url:"assets/espresso.jpg",
       type:"Classic",
       vegan:false,
       will_licks:4.0,
       logan_licks:5.0
    },
    { 
       id:17,
       flavor:"Green Tea",
       img_url:"assets/green-tea.jpg",
       type:"Exotic",
       vegan:true,
       will_licks:4.0,
       logan_licks:4.0
    },
    { 
       id:18,
       flavor:"Rocky Road",
       img_url:"assets/rocky-road.jpg",
       type:"Classic",
       vegan:false,
       will_licks:5.0,
       logan_licks:5.0
    },
    { 
       id:19,
       flavor:"Chocolate Peanut Butter",
       img_url:"assets/chocolate-peanut-butter.jpg",
       type:"Chocolate",
       vegan:false,
       will_licks:2.0,
       logan_licks:4.0
    },
    { 
       id:20,
       flavor:"Pistachio",
       img_url:"assets/pistachio.jpg",
       type:"Nutty",
       vegan:false,
       will_licks:5.0,
       logan_licks:3.0
    },
    { 
       id:21,
       flavor:"Lemon Sorbet",
       img_url:"assets/lemon-sorbet.jpg",
       type:"Fruit",
       vegan:true,
       will_licks:4.0,
       logan_licks:3.0
    },
    { 
       id:22,
       flavor:"Original Tart",
       img_url:"assets/original-tart.jpg",
       type:"Classic",
       vegan:false,
       will_licks:2.0,
       logan_licks:3.0
    }
 ]